### ISSUE TITLE
`SwiftSyntaxParser` was renamed to `SyntaxParser`?

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [keith/swift-syntax-bazel#10]
It looks like `SwiftSyntaxParser` was renamed to `SyntaxParser`, to handle this in our repo we used the following:

```
swift_module_alias(
    name = "SyntaxParser",
    deps = [
        "@com_github_keith_swift_syntax//:SwiftSyntaxParser"
    ],
    module_name = "SyntaxParser"
)
```

Ran into this issue consuming this repository https://github.com/uber/mockolo/blob/master/Package.swift#L14

**Comment by keith** [comment]
SwiftSyntaxParser is the new name https://github.com/apple/swift-syntax/blob/main/Package.swift. HEAD on this repo should have this correct as well

**Comment by tinder-maxwellelliott** [comment]
> SwiftSyntaxParser is the new name https://github.com/apple/swift-syntax/blob/main/Package.swift. HEAD on this repo should have this correct as well

Ahh thank you!
