### ISSUE TITLE
Xcode 13 Compatability

### ISSUE THREAD

**Issue by tinder-owenthomas** [keith/swift-syntax-bazel#3]
We are trying to prepare to adopt Xcode 13 so we are ready when it exits beta, but at the moment it doesn't seem like this repo supports Xcode 13. Since this is used in our build pipeline we are blocked from even building our project in Xcode 13 to identify/address other Xcode 13 compatibility issues.

Is there an estimate for when Xcode 13 compatibility may be addressed? I'm hoping we can have most Xcode 13 issues addressed by early/mid Sept so we are not blocked on Xcode upgrade once it is made available.

**Comment by keith** [comment]
https://github.com/keith/swift-syntax-bazel/releases/tag/13.0.13A5212g

**Comment by keith** [comment]
I will have to do new releases for the later ones, but you can use this with 13.0 beta 5
